# Generated by Django 4.2.7 on 2023-12-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='Dno',
            new_name='Deptno',
        ),
    ]
